sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

language: php

env:
  global:
    - SYMFONY_VERSION=""
    - COMPOSER_OPTIONS="--prefer-stable"

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: COMPOSER_OPTIONS="--prefer-lowest --prefer-stable"
    - php: 7.1
      env: SYMFONY_VERSION="3.4.x"
    - php: 7.2
    - php: 7.3
      env: COVERAGE=yes COMPOSER_OPTIONS="" SYMFONY_PHPUNIT_VERSION=7.5

before_install:
  - if [ "$COVERAGE" != "yes" ]; then phpenv config-rm xdebug.ini; fi
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony:"$SYMFONY_VERSION"; fi

install:
  - composer update $COMPOSER_OPTIONS
  - vendor/bin/simple-phpunit install

script:
  - if [ "$COVERAGE" = "yes" ]; then vendor/bin/simple-phpunit --coverage-clover=coverage.clover; else vendor/bin/simple-phpunit; fi
  - if [ "$COVERAGE" = "yes" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ "$COVERAGE" = "yes" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
